### ISSUE TITLE
Keep a minimum docker compatibility

### ISSUE THREAD

**Issue by dzen** [Polyconseil/grocker#93]
Hello,

Grocker does not freeze the dependencies, and we run a `pip install -U` which means that we always use the latest docker-py libs which has no compatibility with previous versions.

If we have an old docker version we will have an error and our release will fail.

Could we stick to a specific version  please ?

**Comment by fbochu** [comment]
Since https://github.com/Polyconseil/grocker/commit/902f3c256003a1f417505ec930ad1f4d0a6a415f, Grocker require Docker API 1.21.
